language: python
python:
 - "3.6"
 - "3.7"   
#language: cpp

notifications:
  email: false

sudo: true

compiler: gcc

os: linux

before_install:
  - sudo apt-get install -y megatools python3-setuptools python3-pip
  - python3 -m pip install --upgrade pip
  - pip install numpy

  # Install OpenVINO
  - sudo curl -o GPG-PUB-KEY-INTEL-OPENVINO-2020 https://apt.repos.intel.com/openvino/2020/GPG-PUB-KEY-INTEL-OPENVINO-2020
  - sudo apt-key add GPG-PUB-KEY-INTEL-OPENVINO-2020
  - sudo echo "deb https://apt.repos.intel.com/openvino/2020 all main" | sudo tee - a /etc/apt/sources.list.d/intel-openvino-2020.list
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends intel-openvino-dev-ubuntu16-2020.2.130
  # Download test data 
  - wget https://download.01.org/opencv/2020/openvinotoolkit/2020.3/open_model_zoo/models_bin/1/face-detection-0104/FP32/face-detection-0104.bin -O data/face-detection-0104.bin
  - wget https://download.01.org/opencv/2020/openvinotoolkit/2020.2/open_model_zoo/models_bin/3/face-detection-0104/FP32/face-detection-0104.xml -O data/face-detection-0104.xml
    
script:
  - source /opt/intel/openvino/bin/setupvars.sh -pyver 3.5
  - export PYTHONPATH=$(ls modules | xargs -I {} sh -c 'printf $(pwd)/modules/{}:')$PYTHONPATH
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release && make -j8
  
  # Run tests only for changes modules (c++)
  # - git diff --name-only HEAD^ ../modules/ | cut -d "/" -f2 | sed -E "s/[0-9]+_(.*)/\1/" | uniq | xargs -I '{}' sh -c './bin/test_{}'
  
  # Run Python test 
  - python3 -m unittest -v test_detector
  - python3 -m unittest -v test_sourse
  # add new modules here
 
